[[redirects]]
  from = "/sint"
  to = "https://trusting-khorana-2738fe.netlify.app/"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
  signed = "API_SIGNATURE_TOKEN"
